### ISSUE TITLE
context not initialized if using RealScenario evaluation method

### ISSUE THREAD

**Issue by rnithish** [ogreyesp/JCLAL#1]
When trying to use the RandomSelection query strategy with RealScenario evaluation method, the context is not initialized, thereby leaving the Random number generator class object to be null.
Even though we use the RealScenario evaluation method wherein we explicitly specify the labeled and unlabeled data split in two different files, the random number generator is required for the RandomSelection query strategy.

**Comment by mlliarm** [comment]
Hello !

Thank you very much for your feedback. Apologies for replying late.

Kindly provide some more information regarding your system:

1. Operations System: GNU/Linux or MS Windows ? If GNU/Linux, do provide what `sudo lsb_release` gives. Also what `uname -a` gives.
2. Java version: 1.7 or 1.8 ?

In the meantime I'll try to replicate the issue on a Lubuntu 16.04.2 x86_64 and on Windows 7 Professional 64bit, both with Java 1.8, and get back to you. Thanks !

**Comment by rnithish** [comment]
Hello Mi,

Don't spend time on this as of now...I was able to resolve this. I will let you know if it was actually a bug or just a config change that I did in a while.

Thanks,
Nithish

On Jul 21, 2017 16:56, "Mi. Lia." <notifications@github.com> wrote:

Hello !

Thank you very much for your feedback. Apologies for replying that late.

Kindly provide some more information in the following questions:

  1.  Operations System: if GNU/Linux, do write what sudo lsb_release gives. Also what uname -a gives.
  2.  Java version: 1.7 or 1.8 ?

In the meantime I'll try to replicate the issue on a Lubuntu 16.04.2 x86_64 and on Windows 7 Professional 64bit, both with Java 1.8, and get back to you. Thanks !

**Comment by mlliarm** [comment]
@rnithish Thank you very much. I'll leave this issue open until you send those information that did the fix and then close it. Do send more feedback if you encounter any more issues and we'd gladly look into them !

**Comment by ogreyesp** [comment]
Hello, sorry for the delay.

The RealScenario was created to be used in very specific domains where the randomness is needless. Anyway, if you still want to use a random number generator in this type of scenario, you just need to add a line of code to the configure method as follows:

@Override
	public void configure(Configuration configuration) {
		setDataConfiguration(configuration);
		super.setRandGenSettings(configuration);  // This is the new line
		super.setAlgorithmConfiguration(configuration);
}

And, in your xml file, you need to add the xml tag regarding the random factory. For instance

<rand-gen-factory seed="1299961164" type="net.sf.jclal.util.random.RanecuFactory"/>

That it is all.

Thanks for reporting this issue. I'm closing the issue because I saw that you have resolved it.

Oscar

**Comment by ogreyesp** [comment]
Hello, sorry for the delay.

The RealScenario was created to be used in very specific domains where the randomness is needless. Anyway, if you still want to use a random number generator in this type of scenario, you just need to add a line of code to the configure method as follows:

@Override
	public void configure(Configuration configuration) {
		setDataConfiguration(configuration);
		super.setRandGenSettings(configuration);  // This is the new line
		super.setAlgorithmConfiguration(configuration);
}

And, in your xml file, you need to add the xml tag regarding the random factory. For instance

<rand-gen-factory seed="1299961164" type="net.sf.jclal.util.random.RanecuFactory"/>

That it is all.

Thanks for reporting this issue. I'm closing the issue because I saw that you have resolved it.

Oscar

**Comment by rnithish** [comment]
Yes, I have resolved this; and these comments would certainly be useful for others who encounter a similar situation. Thanks!
